require "rake/extensiontask"

gemspec = Gem::Specification.load File.join(__dir__, 'posix_case_conversion.gemspec')

Rake::ExtensionTask.new("posix_case_conversion", gemspec) do |ext|
  ext.lib_dir = "lib/posix_case_conversion"
  ext.ext_dir = 'ext/posix_case_conversion'
end

task default: :compile
